In [1]:
import pandas as pd
# import numpy as np
import scipy as sp
from tqdm.notebook import tqdm

from sklearn.feature_extraction.text import TfidfTransformer, CountVectorizer
from sklearn.neighbors import NearestNeighbors
from sklearn.model_selection import train_test_split

%matplotlib inline

In [2]:
# будем использовать полный набор после отладки на тестовом.
# Полный набор: 
# movies_all = pd.read_csv('../../datasets/movies.csv')
# ratings_all = pd.read_csv('../../datasets/ratings.csv')
# tags_all = pd.read_csv('../../datasets/tags.csv')
# Тестовый набор
movies_all = pd.read_csv('movies.csv')
ratings_all = pd.read_csv('ratings.csv')
tags_all = pd.read_csv('tags.csv')

## Подготовка train-test-split
Объединяем все данные в один большой dataframe с уникальными строками по паре пользователь-фильм,  
делим ее на обучающую и тестовую выборки

In [3]:
# ! Выполнение длится долго (больше минуты) на больших данных
# Все, что дал каждый пользователь в udf.
# Считаем, что пользователя нет, если он не добавил тэг или не проставил рейтинг
tags_all_temp = tags_all.drop(['movieId', 'timestamp'], axis=1, inplace=False)

udf = ratings_all.join(tags_all_temp.set_index('userId'), on='userId') 
# Рейтинг есть у всех фильмов с тэгами?
print(udf[udf.tag.notnull() & udf.rating.isnull()])
umdf = udf.join(movies_all.set_index('movieId'), on='movieId')

Empty DataFrame
Columns: [userId, movieId, rating, timestamp, tag]
Index: []


In [4]:
umdf.head()

userId  movieId  rating  timestamp  tag                        title  \
0       1        1     4.0  964982703  NaN             Toy Story (1995)   
1       1        3     4.0  964981247  NaN      Grumpier Old Men (1995)   
2       1        6     4.0  964982224  NaN                  Heat (1995)   
3       1       47     5.0  964983815  NaN  Seven (a.k.a. Se7en) (1995)   
4       1       50     5.0  964982931  NaN   Usual Suspects, The (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1                               Comedy|Romance  
2                        Action|Crime|Thriller  
3                             Mystery|Thriller  
4                       Crime|Mystery|Thriller

In [5]:
# Выделение тестовой выборки

trdf, testdf, ytr, ytest = train_test_split(umdf.drop(['rating'], axis=1, inplace=False), 
umdf['rating'], 
test_size=0.33, random_state=42)

In [6]:
def change_string(s):
    return ' '.join(s.replace(' ', '').replace('-', '').split('|'))

In [7]:
movie_genres = [change_string(g) for g in trdf.drop_duplicates('movieId').genres.values]


In [8]:

count_vect = CountVectorizer()
X_train_counts = count_vect.fit_transform(movie_genres)
tfidf_transformer = TfidfTransformer()
X_train_tfidf = tfidf_transformer.fit_transform(X_train_counts)
neigh = NearestNeighbors(n_neighbors=7, n_jobs=-1, metric='euclidean') 
neigh.fit(X_train_tfidf)

NearestNeighbors(metric='euclidean', n_jobs=-1, n_neighbors=7)

In [13]:
movie_genres[947]

'Action Adventure Comedy Crime Fantasy'

In [12]:
# Проверка на произвольных жанрах
test = change_string("Adventure|Comedy|Fantasy|Crime")

predict = count_vect.transform([test])
X_tfidf2 = tfidf_transformer.transform(predict)
res = neigh.kneighbors(X_tfidf2, return_distance=True)
# res
print(res)
trdf.iloc[res[1][0]]

(array([[0.41684883, 0.54248378, 0.54248378, 0.54248378, 0.54248378,
        0.54248378, 0.54248378]]), array([[ 947, 6820,  807, 3895, 3949,  786, 6368]], dtype=int64))


userId  movieId   timestamp                  tag  \
25174     177     2355  1435890634            feel-good   
73172     474      296   979179939               racism   
93136     599     1464  1519119509             travolta   
75180     474    52952  1201832936         Stephen King   
73546     474     1573  1100291472             football   
74125     474     3683  1137521116              slasher   
74938     474     8695  1089638396  George Bernard Shaw   

                                          title  \
25174                      Bug's Life, A (1998)   
73172                       Pulp Fiction (1994)   
93136                       Lost Highway (1997)   
75180                    This Is England (2006)   
73546                           Face/Off (1997)   
74125                       Blood Simple (1984)   
74938  Bachelor and the Bobby-Soxer, The (1947)   

                                              genres  
25174            Adventure|Animation|Children|Comedy  
73172                    Comedy|Crime|Drama|Thriller  
93136  Crime|Drama|Fantasy|Film-Noir|Mystery|Romance  
75180                                          Drama  
73546                    Action|Crime|Drama|Thriller  
74125                          Crime|Drama|Film-Noir  
74938                                         Comedy

In [30]:
# Очень неоптимально! медленно даже на небольших данных из-за дублирования всех тэгов всех фильмов
# Использовать другую структуру данных
# и/или переписать цикл на векторыне операции

# Подготовка тэгов - приведение к тому же формату, что и в жанрах
# movies_with_tags.shape
movies_with_tags = trdf.dropna(subset=['tag'], axis = 0,inplace=False)#.drop_duplicates(['tag','movieId'], inplace=False)
# movies_with_tags.head()
print(movies_with_tags[movies_with_tags.tag.isnull()])
n_movies = len(movies_with_tags.drop_duplicates('movieId'))

movies_df = movies_with_tags.drop_duplicates('movieId').drop(['userId','timestamp','tag'], axis=1)
# tag_strings_list = []
# movies_list = []
movies_df['tags'] = ""

for movie, group in tqdm(movies_with_tags.groupby('title')):
    m_tags = '|'.join([str(s).replace(' ', '').replace('-', '') for s in group.tag.values])
    # tag_strings_list.append(m_tags)
    # movies_list.append(movie)
    movies_df.loc[movies_df.movieId == group.movieId.values[0],['tags']] = m_tags

Empty DataFrame
Columns: [userId, movieId, timestamp, tag, title, genres]
Index: []


  0%|          | 0/6358 [00:00<?, ?it/s]

In [31]:
movie_tags = list(movies_df['tags'])
count_vect_tags = CountVectorizer()
X_train_counts_tags = count_vect_tags.fit_transform(movie_tags)
tfidf_transformer_tags = TfidfTransformer()
X_train_tfidf_tags = tfidf_transformer_tags.fit_transform(X_train_counts_tags)
neigh_tags = NearestNeighbors(n_neighbors=7, n_jobs=-1, metric='euclidean') 
neigh_tags.fit(X_train_tfidf_tags)

NearestNeighbors(metric='euclidean', n_jobs=-1, n_neighbors=7)

In [34]:
# Проверка на произвольных тэгах
# test = change_string('pixar|pixar|fun')
test = change_string('darkcomedy|organisedcrime|sophisticated|1990s')

predict = count_vect_tags.transform([test])
X_tfidf2 = tfidf_transformer_tags.transform(predict)

res = neigh_tags.kneighbors(X_tfidf2, return_distance=True)
print(res)
print(res[1][0])
# umdf.head()
# movies_df.iloc[res[1][0]]
movies_df.iloc[res[1][0]]

(array([[1.        , 1.        , 1.28727923, 1.28921858, 1.29021181,
        1.29053042, 1.29067369]]), array([[5970, 5304, 3808, 3438, 3669, 2344, 3809]], dtype=int64))
[5970 5304 3808 3438 3669 2344 3809]


movieId                                              title  \
80596    26958                                        Emma (1996)   
98357    32600                                        Eros (2004)   
94405    26861                                     Freaked (1993)   
94017     5298                                Human Nature (2001)   
94688    63082                         Slumdog Millionaire (2008)   
94871    95165  Dragon Ball Z the Movie: The World's Strongest...   
94878    95499  Dragon Ball Z: Broly - The Legendary Super Sai...   

                                           genres  \
80596                                     Romance   
98357                                       Drama   
94405                               Comedy|Sci-Fi   
94017                              Comedy|Romance   
94688                         Crime|Drama|Romance   
94871  Action|Adventure|Animation|Sci-Fi|Thriller   
94878                  Action|Adventure|Animation   

                                                    tags  
80596                                                     
98357                                                     
94405  meaninglessviolence|disjointedtimeline|nonline...  
94017  artificialintelligence|confusingending|societa...  
94688  action|JeanReno|ArthurC.Clarke|nonlinearnarrat...  
94871  disjointedtimeline|masterpiece|actionpacked|r:...  
94878  sarcasm|gritty|cinematography|organisedcrime|1...

In [17]:
count_vect_t_g = CountVectorizer()
movies_t_g = list(movie_tags) + movie_genres

X_train_counts_tags = count_vect_t_g.fit_transform(movies_t_g)

tfidf_transformer_t_g = TfidfTransformer()
X_train_tfidf_t_g = tfidf_transformer_t_g.fit_transform(X_train_counts_tags)
neigh_t_g = NearestNeighbors(n_neighbors=7, n_jobs=-1, metric='euclidean') 
neigh_t_g.fit(X_train_tfidf_t_g)

NearestNeighbors(metric='euclidean', n_jobs=-1, n_neighbors=7)

In [18]:
# Проверка на произвольных тэгах
# test = change_string('pixar|pixar|fun')
# Проверка на произвольных жанрах
test = change_string('Crime|Mystery|Thriller|Comedy')

predict = count_vect_t_g.transform([test])
X_tfidf2 = tfidf_transformer_t_g.transform(predict)

res = neigh_t_g.kneighbors(X_tfidf2, return_distance=True)
print(res)
print(res[1][0])
# umdf.head()
movies_df.loc[movies_df.movieId == res[1][0][0]]

(array([[0.        , 0.        , 0.        , 0.        , 0.38064277,
        0.38064277, 0.41817673]]), array([[ 9044, 10055,  8987,  8767,  6808, 13440,  6703]], dtype=int64))
[ 9044 10055  8987  8767  6808 13440  6703]


Empty DataFrame
Columns: [movieId, title, genres, tags]
Index: []

Как я понял задачу.  
Нужно оценить рейтинг для фильмов из тестовой выборки двумя способами.

1. по TFIDF жанра и тэгов (без относительно пользователей) построить оценку фильмам с помощью регрессии

Задание "построить рекомендации" в этом случае трактуется так. 
Мы выдадим рейтинги фильмам, которые никто ранее не оценивал, по их тэгам и жанрам. 
Для этого берем ближайших соседей к каждому фильму, усредняем их рейтинг - это значение и задаем как оценку рейтинга.
Пользователь (вне зависимости от предпочтений) получит эти новые фильмы отсортированные в порядке убывания сгенерированного рейтинга.
То есть получит "средние" рекомендации.

2. использовать для вычисления рейтинга (регрессией) средние оценки пользователя и фильма (а также, возможно, другие метрики)

Задание "построить рекомендации" в этом случае трактуется так. 
Получается большой вектор со строками "пользователь-фильм" длины равной длине вектора ratings. На таком векторе мы должны обучить регрессию и для такого же тестового вектора предсказать оценки.
В качестве фич можно использовать такие:
* средняя оценка фильма
* средняя оценка пользователя
* средняя оценка фильмов этого жанра (всеми пользователями)
* средняя оценка фильмов этого жанра (этим пользователем)
* (под сомнением) средняя оценка этого фильма любителями этого жанра (любитель - пользователь оценивший больше фильмов этого жанра, чем другие пользователи в среднем) - не факт, что поможет, т.к. больше всего оценок генерил персонал сервиса, как было показано в материалах к лекции


